### ISSUE TITLE
Add MRL recommended IP node ban list

### ISSUE THREAD

**Issue by rottenwheel** [rblaine95/docker-monero#42]
- Issue: https://github.com/monero-project/meta/issues/1124
- Ban list: https://github.com/Boog900/monero-ban-list

**Comment by rblaine95** [comment]
Hey @rottenwheel, thank you for opening the issue.

I'm not sure about packaging a ban list in the docker image.

If you want to use the ban list, you can simply:
`wget https://raw.githubusercontent.com/Boog900/monero-ban-list/refs/heads/main/ban_list.txt -O ./monero-data/ban_list.txt`
and then in Docker Compose (for example):
```yaml
  monerod:
    container_name: monerod
    image: ghcr.io/rblaine95/monero
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./monero-data:/opt/bitmonero
    command:
      - --ban-list=/opt/bitmonero/ban_list.txt
```
Or:
```bash
docker run \
  -dit \
  --restart=always \
  --net=host \
  --name=monerod \
  -v /path/to/bitmonero:/opt/bitmonero \
  ghcr.io/rblaine95/monero \
    --ban-list=/opt/bitmonero/ban_list.txt
```

I'm happy to discuss packaging the ban list directly in the docker image, however, ultimately, I think it's up to whoever uses this docker image whether they want to use the list or not.

Maybe, instead of packaging the ban list in the image itself I can add examples in the Docker Compose and Readme on acquiring the ban list and linking to the issue?
